### ISSUE TITLE
Reserve Now / Cancel Reservation not necessary anymore?

### ISSUE THREAD

**Issue by goekay** [RWTH-i5-IDSG/ps-cms-protocol#2]
Since backend is handling all the logic related to providing available pedelecs, the role of the station is rather displaying the provided pedelec and allowing the customer to take it.

In this case, should we deprecate these two functions? What could the station do with reservation information?

**Comment by csamsel** [comment]
turning an LED red or display it maybe?

**Comment by wollodev** [comment]
That's true. It will stay for state indication (reserved, free) by the station.
